### ISSUE TITLE
Missing Controller on both Organization, Contacts & Reports links

### ISSUE THREAD

**Issue by elmesero** [ishanvyas22/cakephp-pingcrm#31]
Hi Ishan,

I managed to install everything, log in, and landed on dashboard page.

However, when I click on sidebar links to Organizations, Contacts, and Reports, I get Cake's MissingControllerException. Users, on the other hand, exists and is working fine.

I noticed you don't have a controller for any of the 3, so I used bake to generate them.

Now I'm able to load the Organizations/index page, but I'm getting a "TypeError: _vm.route is not a function".

Thanks

**Comment by ishanvyas22** [comment]
I would suggest you check out the code from the [UsersController](https://github.com/ishanvyas22/cakephp-pingcrm/blob/master/src/Controller/UsersController.php#L22) and it's related vue file [resources/js/Pages/Users/Index.vue](https://github.com/ishanvyas22/cakephp-pingcrm/blob/master/resources/js/Pages/Users/Index.vue). I've made this file as a reference, it should work in most cases and if you look and check it properly you might be able to solve it your own.

If it doesn't solve then can you share some code, screenshot or something so I can help you better?

**Comment by elmesero** [comment]
Ok. Got it.

I assumed the links on the sidebar were supposed to work, that's why I asked.

Thanks.

**Comment by ishanvyas22** [comment]
No problem :) Feel free to submit a PR once you are able to make it work. It'll help others.
